import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/education.json'
import { useState } from 'react'
import Card from '../components/Card'
import NavBar from '../components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  console.log(data);
  const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>Programs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar/>
        <div className={styles.grid}>
          <div>Business Degree:
          {information && information.map((info, index) => {
            if(info.department.toLowerCase() === "business") {
              return(
                <Card key={index} degree={info.degree} color="red" font="10px"/>
              )
            }
          })}
          </div>
        
          <div>Computing Degrees:
          {information && information.map((info, index) => {
            if(info.department.toLowerCase() === "computing") {
              return(
                <Card key={index} degree={info.degree} color="blue" font="20px"/>
              )
            }
          })}
          </div>
        </div>
      </main>
    </>
  )
}
